2024-04-12 17:45:57,787:ERROR:An error occurred when calling message handler
Traceback (most recent call last):
  File "D:\py\pr\email_automation_tool\venv\Lib\site-packages\pystray\_win32.py", line 412, in _dispatcher
    return int(icon._message_handlers.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\py\pr\email_automation_tool\venv\Lib\site-packages\pystray\_win32.py", line 224, in _on_notify
    descriptors[index - 1](self)
  File "D:\py\pr\email_automation_tool\venv\Lib\site-packages\pystray\_base.py", line 328, in inner
    callback(self)
  File "D:\py\pr\email_automation_tool\venv\Lib\site-packages\pystray\_base.py", line 453, in __call__
    return self._action(icon, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\py\pr\email_automation_tool\background.py", line 139, in on_clicked
    icon.stop()
  File "D:\py\pr\email_automation_tool\venv\Lib\site-packages\pystray\_base.py", line 252, in stop
    self._setup_thread.join(timeout=self.SETUP_THREAD_TIMEOUT)
  File "C:\Python312\Lib\threading.py", line 1130, in join
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "C:\Python312\Lib\threading.py", line 1146, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-04-12 17:47:21,315:ERROR:An error occurred when calling message handler
Traceback (most recent call last):
  File "D:\py\pr\email_automation_tool\venv\Lib\site-packages\pystray\_win32.py", line 412, in _dispatcher
    return int(icon._message_handlers.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\py\pr\email_automation_tool\venv\Lib\site-packages\pystray\_win32.py", line 224, in _on_notify
    descriptors[index - 1](self)
  File "D:\py\pr\email_automation_tool\venv\Lib\site-packages\pystray\_base.py", line 328, in inner
    callback(self)
  File "D:\py\pr\email_automation_tool\venv\Lib\site-packages\pystray\_base.py", line 453, in __call__
    return self._action(icon, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\py\pr\email_automation_tool\background.py", line 150, in on_clicked
    icon.stop()
  File "D:\py\pr\email_automation_tool\venv\Lib\site-packages\pystray\_base.py", line 252, in stop
    self._setup_thread.join(timeout=self.SETUP_THREAD_TIMEOUT)
  File "C:\Python312\Lib\threading.py", line 1130, in join
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "C:\Python312\Lib\threading.py", line 1146, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-04-12 17:47:33,680:ERROR:An error occurred when calling message handler
Traceback (most recent call last):
  File "D:\py\pr\email_automation_tool\venv\Lib\site-packages\pystray\_win32.py", line 412, in _dispatcher
    return int(icon._message_handlers.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\py\pr\email_automation_tool\venv\Lib\site-packages\pystray\_win32.py", line 224, in _on_notify
    descriptors[index - 1](self)
  File "D:\py\pr\email_automation_tool\venv\Lib\site-packages\pystray\_base.py", line 328, in inner
    callback(self)
  File "D:\py\pr\email_automation_tool\venv\Lib\site-packages\pystray\_base.py", line 453, in __call__
    return self._action(icon, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\py\pr\email_automation_tool\background.py", line 150, in on_clicked
    icon.stop()
  File "D:\py\pr\email_automation_tool\venv\Lib\site-packages\pystray\_base.py", line 252, in stop
    self._setup_thread.join(timeout=self.SETUP_THREAD_TIMEOUT)
  File "C:\Python312\Lib\threading.py", line 1130, in join
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "C:\Python312\Lib\threading.py", line 1146, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-04-12 18:21:52,868:WARNING:The function passed as setup to the icon did not finish within 5.0 seconds after icon was stopped
2024-04-12 18:43:05,533:ERROR:An error occurred when calling message handler
Traceback (most recent call last):
  File "D:\py\pr\Outook_Automation_Tool\.venv\Lib\site-packages\pystray\_win32.py", line 412, in _dispatcher
    return int(icon._message_handlers.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\py\pr\Outook_Automation_Tool\.venv\Lib\site-packages\pystray\_win32.py", line 224, in _on_notify
    descriptors[index - 1](self)
  File "D:\py\pr\Outook_Automation_Tool\.venv\Lib\site-packages\pystray\_base.py", line 328, in inner
    callback(self)
  File "D:\py\pr\Outook_Automation_Tool\.venv\Lib\site-packages\pystray\_base.py", line 453, in __call__
    return self._action(icon, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\py\pr\Outook_Automation_Tool\background.py", line 150, in on_clicked
    icon.stop()
  File "D:\py\pr\Outook_Automation_Tool\.venv\Lib\site-packages\pystray\_base.py", line 252, in stop
    self._setup_thread.join(timeout=self.SETUP_THREAD_TIMEOUT)
  File "C:\Python312\Lib\threading.py", line 1130, in join
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "C:\Python312\Lib\threading.py", line 1146, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-04-12 18:43:06,835:ERROR:An error occurred when calling message handler
Traceback (most recent call last):
  File "D:\py\pr\Outook_Automation_Tool\.venv\Lib\site-packages\pystray\_win32.py", line 412, in _dispatcher
    return int(icon._message_handlers.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\py\pr\Outook_Automation_Tool\.venv\Lib\site-packages\pystray\_win32.py", line 224, in _on_notify
    descriptors[index - 1](self)
  File "D:\py\pr\Outook_Automation_Tool\.venv\Lib\site-packages\pystray\_base.py", line 328, in inner
    callback(self)
  File "D:\py\pr\Outook_Automation_Tool\.venv\Lib\site-packages\pystray\_base.py", line 453, in __call__
    return self._action(icon, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\py\pr\Outook_Automation_Tool\background.py", line 150, in on_clicked
    icon.stop()
  File "D:\py\pr\Outook_Automation_Tool\.venv\Lib\site-packages\pystray\_base.py", line 252, in stop
    self._setup_thread.join(timeout=self.SETUP_THREAD_TIMEOUT)
  File "C:\Python312\Lib\threading.py", line 1130, in join
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "C:\Python312\Lib\threading.py", line 1146, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-04-12 18:45:59,341:WARNING:The function passed as setup to the icon did not finish within 5.0 seconds after icon was stopped
2024-04-12 19:00:12,072:WARNING:The function passed as setup to the icon did not finish within 5.0 seconds after icon was stopped
2024-04-12 19:22:24,873:WARNING:The function passed as setup to the icon did not finish within 5.0 seconds after icon was stopped
2024-04-12 19:47:54,471:WARNING:The function passed as setup to the icon did not finish within 5.0 seconds after icon was stopped
2024-04-12 19:50:09,552:WARNING:The function passed as setup to the icon did not finish within 5.0 seconds after icon was stopped
2024-04-12 19:50:12,302:WARNING:The function passed as setup to the icon did not finish within 5.0 seconds after icon was stopped
2024-04-12 20:18:03,219:ERROR:An error occurred when calling message handler
Traceback (most recent call last):
  File "D:\py\pr\Outook_Automation_Tool\.venv\Lib\site-packages\pystray\_win32.py", line 412, in _dispatcher
    return int(icon._message_handlers.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\py\pr\Outook_Automation_Tool\.venv\Lib\site-packages\pystray\_win32.py", line 224, in _on_notify
    descriptors[index - 1](self)
  File "D:\py\pr\Outook_Automation_Tool\.venv\Lib\site-packages\pystray\_base.py", line 328, in inner
    callback(self)
  File "D:\py\pr\Outook_Automation_Tool\.venv\Lib\site-packages\pystray\_base.py", line 453, in __call__
    return self._action(icon, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\py\pr\Outook_Automation_Tool\.venv\Lib\site-packages\pystray\_base.py", line 548, in wrapper0
    return action()
           ^^^^^^^^
  File "D:\py\pr\Outook_Automation_Tool\background.pyw", line 28, in open_home_screen
    app = HomeApp(root)  # Assuming HomeApp is your main application class
          ^^^^^^^^^^^^^
  File "D:\py\pr\Outook_Automation_Tool\home.py", line 37, in __init__
    self.background_process.start()
  File "C:\Python312\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\multiprocessing\context.py", line 337, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\multiprocessing\spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "C:\Python312\Lib\multiprocessing\spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html
        
2024-04-12 20:18:37,430:WARNING:The function passed as setup to the icon did not finish within 5.0 seconds after icon was stopped
2024-04-12 20:18:40,211:WARNING:The function passed as setup to the icon did not finish within 5.0 seconds after icon was stopped
